/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarGroup: typeof import('./src/components/AvatarGroup.vue')['default']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupDescription: typeof import('@headlessui/vue')['RadioGroupDescription']
    RadioGroupLabel: typeof import('@headlessui/vue')['RadioGroupLabel']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    RadioList: typeof import('./src/components/RadioList.vue')['default']
    RoomCard: typeof import('./src/components/RoomCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    ElementHover: typeof import('@vueuse/components')['vElementHover']
  }
}
