
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"ADD#16" | "ADD" | "Game Guild" | "MentorwithIcon" | "Notice-unread" | "Notice" | "Play with" | "PlaywithIcon" | "Window+" | "Window-" | "add emoji" | "arrow-down-s-fill" | "arrow-right-s-fill" | "arrow-up-s-fill" | "back" | "battle" | "channel-settings" | "channel-share" | "chart" | "close Window" | "contacts-fill" | "copy" | "corner-down" | "custom" | "delete" | "emotion-fill" | "female" | "folder-open" | "folder" | "game" | "group" | "group24" | "headphone-off" | "headphone" | "image-edit" | "link" | "lock#12" | "lock" | "logout" | "male" | "mic-fill#12" | "mic-off-fill#12" | "mic-off" | "mic" | "new massage" | "new-friend" | "no" | "notification-fill" | "notification-off-fill" | "offline" | "online" | "people" | "person_card" | "personal community" | "phone" | "presentation-fill#24" | "presentation-fill" | "reply" | "screenshot-fill" | "search#24" | "search" | "set" | "settings" | "shut-down" | "sound-module" | "subtract" | "team" | "text-normal" | "text-unread" | "user-forbid" | "user-received-fill32" | "user-received" | "user-received2" | "user_card" | "volume#12" | "volume-mute-fill" | "volume-open-fill" | "volume" | "warning" | "yes" | "人员设置" | "控制器">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"ADD#16" | "ADD" | "Game Guild" | "MentorwithIcon" | "Notice-unread" | "Notice" | "Play with" | "PlaywithIcon" | "Window+" | "Window-" | "add emoji" | "arrow-down-s-fill" | "arrow-right-s-fill" | "arrow-up-s-fill" | "back" | "battle" | "channel-settings" | "channel-share" | "chart" | "close Window" | "contacts-fill" | "copy" | "corner-down" | "custom" | "delete" | "emotion-fill" | "female" | "folder-open" | "folder" | "game" | "group" | "group24" | "headphone-off" | "headphone" | "image-edit" | "link" | "lock#12" | "lock" | "logout" | "male" | "mic-fill#12" | "mic-off-fill#12" | "mic-off" | "mic" | "new massage" | "new-friend" | "no" | "notification-fill" | "notification-off-fill" | "offline" | "online" | "people" | "person_card" | "personal community" | "phone" | "presentation-fill#24" | "presentation-fill" | "reply" | "screenshot-fill" | "search#24" | "search" | "set" | "settings" | "shut-down" | "sound-module" | "subtract" | "team" | "text-normal" | "text-unread" | "user-forbid" | "user-received-fill32" | "user-received" | "user-received2" | "user_card" | "volume#12" | "volume-mute-fill" | "volume-open-fill" | "volume" | "warning" | "yes" | "人员设置" | "控制器">;
            default: string;
            required: true;
        };
    }>>, {
        name: "ADD#16" | "ADD" | "Game Guild" | "MentorwithIcon" | "Notice-unread" | "Notice" | "Play with" | "PlaywithIcon" | "Window+" | "Window-" | "add emoji" | "arrow-down-s-fill" | "arrow-right-s-fill" | "arrow-up-s-fill" | "back" | "battle" | "channel-settings" | "channel-share" | "chart" | "close Window" | "contacts-fill" | "copy" | "corner-down" | "custom" | "delete" | "emotion-fill" | "female" | "folder-open" | "folder" | "game" | "group" | "group24" | "headphone-off" | "headphone" | "image-edit" | "link" | "lock#12" | "lock" | "logout" | "male" | "mic-fill#12" | "mic-off-fill#12" | "mic-off" | "mic" | "new massage" | "new-friend" | "no" | "notification-fill" | "notification-off-fill" | "offline" | "online" | "people" | "person_card" | "personal community" | "phone" | "presentation-fill#24" | "presentation-fill" | "reply" | "screenshot-fill" | "search#24" | "search" | "set" | "settings" | "shut-down" | "sound-module" | "subtract" | "team" | "text-normal" | "text-unread" | "user-forbid" | "user-received-fill32" | "user-received" | "user-received2" | "user_card" | "volume#12" | "volume-mute-fill" | "volume-open-fill" | "volume" | "warning" | "yes" | "人员设置" | "控制器";
    }>;
  }
}
